---
galaxy_info:
  role_name: gc_node
  namespace: protofire
  author: protofire
  description: >
    Ansible role that deploy Nethermind Node for Gnosis Chain (GC)

  license: GPLv3

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
    - name: Debian
    - name: CentOS
    - name: Fedora
    - name: Amazon Linux 2

  galaxy_tags:
    - gcnode

dependencies: []
