---
- name: Install docker [Debian-based]
  vars:
    distr: "{{ ansible_distribution | lower }}"
  block:
    - name: Install prerequisites [Debian-based]
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - "{{ debian_docker_package_dependencies }}"
        - libffi-dev


    - name: Import Docker GPG signing key [Debian-based]
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ distr }}/gpg"
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository [Debian-based]
      vars:
        arch: "{{ 'arm64' if ansible_machine == 'aarch64' else 'amd64' }}"
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ arch }}
          signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/{{ distr }}
          {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        update_cache: true

    - name: Install Docker and its dependencies [Debian-based]
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: "{{ docker_package_state }}"
        update_cache: true
      notify: Restart Docker
